### PR TITLE
company info added

### PR DESCRIPTION
**Pull request by satya1657**

### CODE REVIEW

**Review by Satyaprkash-Sigmoid — COMMENTED** [review]
Okay It is good add your home town info also

**Comment by satya1657** [comment]
> Okay It is good add your home town info also

yes sure

**Review by Satyaprkash-Sigmoid — COMMENTED** [review]
add your school info also

**Comment by satya1657** [comment]
sure

**Comment by Satyaprkash-Sigmoid** [comment]
merged

**Pull request merged**
